More Python 3 fixes needed to also install the packages
Daemon still does not start. It fails as follows:

Traceback (most recent call last):
  File "/usr/share/wicd/daemon/wicd-daemon.py", line 62, in <module>
    from wicd.logfile import ManagedStdio
  File "/usr/lib/python3/dist-packages/wicd/logfile.py", line 32, in <module>
    class LogFile(file):
NameError: name 'file' is not defined